config/routes.rb
require "custom_domain"

Rails.application.routes.draw do
  constraints CustomDomain do
    root to: "schools#show" do
      get "admin", to: "admins#show"
      devise_scope :student do
        get "students/sign_in", to: "students/sessions#new"
        get "students/sign_out", to: "students/sessions#destroy"
      end
      devise_scope :teacher do
        get "teachers/sign_in", to: "teachers/sessions#new"
        get "teachers/sign_out", to: "teachers/sessions#destroy"
      end
      resources :blogs
      resources :grades, only: [:edit, :create, :destroy, :update, :show] do
        resources :courses, only: [:show] do
          member do
            get :followers, :course_teachers
          end
        end
        member do
          get :grade_teachers
        end
      end
      resources :students, only: [:show] do
        member do
          get :following
        end
      end
      resources :teachers, only: [:show] do
        member do
          get :grade_taught, :course_taught
        end
      end
    end
  end

  devise_for :admins, controllers: {
                        registrations: "admins/registrations",
                        sessions: "admins/sessions",
                      }
  devise_for :students, controllers: {
                          registrations: "students/registrations",
                          sessions: "students/sessions",
                        }
  devise_for :teachers, controllers: {
                          registrations: "teachers/registrations",
                          sessions: "teachers/sessions",
                        }
  resources :notes
  resources :tests
  resources :assignments
  resources :test_scores
  resources :assignment_scores
  resources :blogs
  resources :courses, only: [:edit, :create, :destroy, :update]
  resources :schools, except: [:destroy] do
    devise_scope :student do
      get "students/sign_in", to: "students/sessions#new"
      get "students/sign_out", to: "students/sessions#destroy"
    end
    devise_scope :teacher do
      get "teachers/sign_in", to: "teachers/sessions#new"
      get "teachers/sign_out", to: "teachers/sessions#destroy"
    end
    resources :blogs
    resources :grades, only: [:edit, :create, :destroy, :update, :show] do
      resources :courses, only: [:show] do
        member do
          get :followers, :course_teachers
        end
      end
      member do
        get :grade_teachers
      end
    end
    resources :students, only: [:show] do
      member do
        get :following
      end
    end
    resources :teachers, only: [:show] do
      member do
        get :grade_taught, :course_taught
      end
    end
  end

  get "/", to: "home#index"

  resources :admins, :only => [:show] do
    get "/createstudent", to: "admins#create_students"
    get "/createteacher", to: "admins#create_teachers"
    get "/classes", to: "admins#classes"
    get "/posts", to: "admins#posts"
    get "/domain", to: "admins#domain"
  end
  resources :student_courses, only: [:create, :destroy]
  resources :teacher_courses, only: [:create, :destroy]
  resources :teacher_grades, only: [:create, :destroy]
  get "schools/:id/admin", to: "admins#show"
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :school

    mount_uploader :image, FileUploader
  serialize :image, JSON
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @school = School.find_by(id: @blog.school_id)
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to school_blog_path(current_admin.school.id, @blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :description, :image, :school_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= simple_form_for(@blog) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :descripiton %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Descripiton</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><img src="<%= blog.image %>" class="img-thumbnail" /></td>
        <td><%= blog.title %></td>
        <td><%= blog.description %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<%= render 'schools/main_header' %>
  <!-- Page Header -->
  <header class="masthead" style="background-image: url(<%= @blog.image_url %>);background-size: cover; background-position: center;">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1><%= @blog.title %></h1>
            <span class="meta">Posted on <%= @blog.created_at %></span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p><%= @blog.description %></p>
        </div>
      </div>
    </div>
  </article>

  <hr>
  <%= render 'schools/footer' %>