config/routes.rb
require "custom_domain"

Rails.application.routes.draw do
  constraints CustomDomain do
    root to: "schools#show" do
      get "admin", to: "admins#show"
      devise_scope :student do
        get "students/sign_in", to: "students/sessions#new"
        get "students/sign_out", to: "students/sessions#destroy"
      end
      devise_scope :teacher do
        get "teachers/sign_in", to: "teachers/sessions#new"
        get "teachers/sign_out", to: "teachers/sessions#destroy"
      end
      resources :blogs
      resources :grades, only: [:edit, :create, :destroy, :update, :show] do
        resources :courses, only: [:show] do
          member do
            get :followers, :course_teachers
          end
        end
        member do
          get :grade_teachers
        end
      end
      resources :students, only: [:show] do
        member do
          get :following
        end
      end
      resources :teachers, only: [:show] do
        member do
          get :grade_taught, :course_taught
        end
      end
    end
  end

  devise_for :admins, controllers: {
                        registrations: "admins/registrations",
                        sessions: "admins/sessions",
                      }
  devise_for :students, controllers: {
                          registrations: "students/registrations",
                          sessions: "students/sessions",
                        }
  devise_for :teachers, controllers: {
                          registrations: "teachers/registrations",
                          sessions: "teachers/sessions",
                        }
  resources :notes
  resources :tests
  resources :assignments
  resources :test_scores
  resources :assignment_scores
  resources :blogs
  resources :courses, only: [:edit, :create, :destroy, :update]
  resources :schools, except: [:destroy] do
    devise_scope :student do
      get "students/sign_in", to: "students/sessions#new"
      get "students/sign_out", to: "students/sessions#destroy"
    end
    devise_scope :teacher do
      get "teachers/sign_in", to: "teachers/sessions#new"
      get "teachers/sign_out", to: "teachers/sessions#destroy"
    end
    resources :blogs
    resources :grades, only: [:edit, :create, :destroy, :update, :show] do
      resources :courses, only: [:show] do
        member do
          get :followers, :course_teachers
        end
      end
      member do
        get :grade_teachers
      end
    end
    resources :students, only: [:show] do
      member do
        get :following
      end
    end
    resources :teachers, only: [:show] do
      member do
        get :grade_taught, :course_taught
      end
    end
  end

  get "/", to: "home#index"

  resources :admins, :only => [:show] do
    get "/createstudent", to: "admins#create_students"
    get "/createteacher", to: "admins#create_teachers"
    get "/classes", to: "admins#classes"
    get "/posts", to: "admins#posts"
    get "/domain", to: "admins#domain"
  end
  resources :student_courses, only: [:create, :destroy]
  resources :teacher_courses, only: [:create, :destroy]
  resources :teacher_grades, only: [:create, :destroy]
  get "schools/:id/admin", to: "admins#show"
end

app/views/admins/_dashend.html.erb
</div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>


<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="card-body text-center">
        <h4 class="card-title">Upload</h4>
      </div>
      <div class=" card col-8 offset-2 my-2 p-3">
        <%= render 'schools/schoolform' %>
      </div>
    </div>
  </div>
</div>

app/views/admins/classes.html.erb
<%= render 'dash' %>
<!-- Begin Page Content -->
<div class="container-fluid">
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Welcome!</strong> click create class button and enter the name of your class e.g 1 blue. To create a course for the class just click the name of the class
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <!-- Page Heading -->
  <h1>Classes</h1>
  <button id="add__new__list" type="button" class="btn btn-success" data-toggle="modal" data-target=".bd-example-modal-lg"><i class="fa fa-plus"></i> Create class</button>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Class</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @classes.each do |grade| %>
        <tr>
          <td><%= link_to grade.name, [grade.school, grade] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="card-body text-center">
        <h4 class="card-title">Upload</h4>
      </div>
      <div class=" card col-8 offset-2 my-2 p-3">
        <%= form_for [current_admin.school, Grade.new] do |f| %>
        <div class="form-inputs">
            <%= f.label :name %>
            <%= f.text_field :name, required: true, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.hidden_field :school_id, value: current_admin.school.id %>
        </div>
        <div class="form-actions">
            <%= f.button :submit %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- /.container-fluid -->
<%= render 'dashend' %>

app/views/admins/create_students.html.erb
<%= render 'dash' %>
<!-- Begin Page Content -->
<div class="container-fluid">
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Welcome!</strong> click create student to add students to your school. To assign a course to a student just click the name of the student and you will be taken to the student dashboard on the left side you will see the add course button.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <!-- Page Heading -->
  <%= link_to "Create Student", new_student_registration_path, class: "btn btn-success" %>
  <h1>Students</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @school_students.each do |student| %>
        <tr>
          <td><%= link_to student.name, [student.school, student] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>
<!-- /.container-fluid -->
<%= render 'dashend' %>

app/views/admins/create_teachers.html.erb
<% if @school_teachers %>
<%= render 'dash' %>
<!-- Begin Page Content -->
<div class="container-fluid">
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Welcome!</strong> click create teacher to add teachers to your school. To assign a course/class to a teacher just click the name of the teacher and you will be taken to the teacher dashboard on the left side you will see the manage course/grades button.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <!-- Page Heading -->
  <%= link_to "Create Teacher", new_teacher_registration_path, class: "btn btn-success" %>
  <h1>Teachers</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @school_teachers.each do |teacher| %>
        <tr>
          <td><%= link_to teacher.name, [teacher.school, teacher] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>
<!-- /.container-fluid -->
<%= render 'dashend' %>
<% else %>
  <h1 class="text-center pt-5">You dont have access to the page</h1>
<% end %>

app/views/admins/domain.html.erb
<%= render 'dash' %>
<!-- Begin Page Content -->
<div class="container-fluid">
  <!-- Page Heading -->
    <div class="row justify-content-center">
        <h3>Buy your school domain name</h3>
        <div class="col-12 col-md-10 col-lg-8 my-3">
            <form >
                <div class="row no-gutters align-items-center form-group">
                    <div class="col-9">
                        <input aria-describedby="domainHelp" class="form-control form-control-lg form-control-borderless" type="search" placeholder="e.g schoolname.ac.zw">
                    </div>
                    <!--end of col-->
                    <div class="col-auto">
                        <button class="btn btn-lg btn-primary" type="submit"><i class="fa fa-search h4 text-white text-body"></i></button>
                    </div>
                    <!--end of col-->
                    <small id="domainHelp" class="form-text text-muted">Search to see if the domain name is available.</small>
                </div>
            </form>
        </div>
        <!--end of col-->
    </div>
    <hr>
    <h3>IF you already have a domain put the nameservers here</h3>
    <form>
        <div class="row my-2">
            <div class="col">
            <input type="text" class="form-control" placeholder="nameserver 1">
            </div>
            <div class="col">
            <input type="text" class="form-control" placeholder="nameserver 2">
            </div>
        </div>
        <div class="row my-2">
            <div class="col">
            <input type="text" class="form-control" placeholder="nameserver 3">
            </div>
            <div class="col">
            <input type="text" class="form-control" placeholder="nameserver 4">
            </div>
        </div>
        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Make these default</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
<!-- /.container-fluid -->
<%= render 'dashend' %>

app/views/admins/posts.html.erb
<%= render 'dash' %>
<!-- Begin Page Content -->
<div class="container-fluid">
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Welcome!</strong> Here you can create posts which will be read by anyone who visits your website, these can be important notices or events that will take place or which took place.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <!-- Page Heading -->
  <h1>Posts</h1>
  <button id="add__new__list" type="button" class="btn btn-success" data-toggle="modal" data-target=".bd-example-modal-lg">
  <i class="fa fa-plus"></i> Create post
  </button>
   <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" class="border-0 bg-light">
                    <div class="p-2 px-3 text-uppercase">Title</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Remove</div>
                  </th>
                </tr>
              </thead>
              <tbody>
               <% @blogs.each do |post| %>
                <tr>
                  <th scope="row" class="border-0">
                    <div class="p-2 resize">
                    <%= image_tag post.image_url class: "shadow-sm" %>
                      <div class="ml-3 d-inline-block align-middle">
                        <h5 class="mb-0"> <a href="#" class="text-dark d-inline-block align-middle"><%= link_to post.title, [post.school, post] %></a></h5>
                      </div>
                    </div>
                  </th>
                  <td class="border-0 align-middle"><a href="#" class="text-dark"><i class="fa fa-trash"></i></a></td>
                </tr>
               <% end %>
              </tbody>
            </table>
        </div>
  <br>
</div>
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="card-body text-center">
        <h4 class="card-title">Post</h4>
      </div>
      <div class=" card col-8 offset-2 my-2 p-3">
        <%= form_for [current_admin.school, Blog.new] do |f| %>
        <div class="form-inputs">
            <%= f.label :image %>
            <%= f.file_field :image, class: "form-control" %>
        </div>
        <div class="form-inputs">
            <%= f.label :title %>
            <%= f.text_field :title, required: true, class: "form-control" %>
        </div>
        <div class="form-inputs">
            <%= f.label :description %>
            <%= f.text_field :description, required: true, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.hidden_field :school_id, value: current_admin.school.id %>
        </div>
        <div class="form-actions">
            <%= f.button :submit %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- /.container-fluid -->
<%= render 'dashend' %>

app/views/admins/show.html.erb
<%= render 'dash' %>
<!-- Begin Page Content -->
<div class="container-fluid">
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Welcome!</strong> create at least 1 class if you do not have any, so that the students, teachers section will appear in the left side of the admin panel. Click at the link classes on your left side
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">Progress Information</h1>
</div>
<!-- /.container-fluid -->
<%= render 'dashend' %>