config/routes.rb
require "custom_domain"

Rails.application.routes.draw do
  constraints CustomDomain do
    root to: "schools#show" do
      get "admin", to: "admins#show"
      devise_scope :student do
        get "students/sign_in", to: "students/sessions#new"
        get "students/sign_out", to: "students/sessions#destroy"
      end
      devise_scope :teacher do
        get "teachers/sign_in", to: "teachers/sessions#new"
        get "teachers/sign_out", to: "teachers/sessions#destroy"
      end
      resources :blogs
      resources :grades, only: [:edit, :create, :destroy, :update, :show] do
        resources :courses, only: [:show] do
          member do
            get :followers, :course_teachers
          end
        end
        member do
          get :grade_teachers
        end
      end
      resources :students, only: [:show] do
        member do
          get :following
        end
      end
      resources :teachers, only: [:show] do
        member do
          get :grade_taught, :course_taught
        end
      end
    end
  end

  devise_for :admins, controllers: {
                        registrations: "admins/registrations",
                        sessions: "admins/sessions",
                      }
  devise_for :students, controllers: {
                          registrations: "students/registrations",
                          sessions: "students/sessions",
                        }
  devise_for :teachers, controllers: {
                          registrations: "teachers/registrations",
                          sessions: "teachers/sessions",
                        }
  resources :notes
  resources :tests
  resources :assignments
  resources :test_scores
  resources :assignment_scores
  resources :blogs
  resources :courses, only: [:edit, :create, :destroy, :update]
  resources :schools, except: [:destroy] do
    devise_scope :student do
      get "students/sign_in", to: "students/sessions#new"
      get "students/sign_out", to: "students/sessions#destroy"
    end
    devise_scope :teacher do
      get "teachers/sign_in", to: "teachers/sessions#new"
      get "teachers/sign_out", to: "teachers/sessions#destroy"
    end
    resources :blogs
    resources :grades, only: [:edit, :create, :destroy, :update, :show] do
      resources :courses, only: [:show] do
        member do
          get :followers, :course_teachers
        end
      end
      member do
        get :grade_teachers
      end
    end
    resources :students, only: [:show] do
      member do
        get :following
      end
    end
    resources :teachers, only: [:show] do
      member do
        get :grade_taught, :course_taught
      end
    end
  end

  get "/", to: "home#index"

  resources :admins, :only => [:show] do
    get "/createstudent", to: "admins#create_students"
    get "/createteacher", to: "admins#create_teachers"
    get "/classes", to: "admins#classes"
    get "/posts", to: "admins#posts"
    get "/domain", to: "admins#domain"
  end
  resources :student_courses, only: [:create, :destroy]
  resources :teacher_courses, only: [:create, :destroy]
  resources :teacher_grades, only: [:create, :destroy]
  get "schools/:id/admin", to: "admins#show"
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  attr_accessor :login
  validates_uniqueness_of :username
  belongs_to :school

  has_many :active_teacher_grades, class_name: "TeacherGrade",
                                   foreign_key: "follower_id",
                                   dependent: :destroy
  has_many :grade_taught, through: :active_teacher_grades, source: :followed

  has_many :active_teacher_courses, class_name: "TeacherCourse",
                                    foreign_key: "follower_id",
                                    dependent: :destroy
  has_many :course_taught, through: :active_teacher_courses, source: :followed

  # Follows a grade.
  def add_teacher_to_grade(other_grade)
    grade_taught << other_grade unless self == other_grade
  end

  # Unfollows a grade.
  def remove_teacher_from_grade(other_grade)
    grade_taught.delete(other_grade)
  end

  # Returns true if the teacher is teaching other grade.
  def grade_taught?(other_grade)
    grade_taught.include?(other_grade)
  end

  # Follows a course.
  def add_teacher_to_course(other_course)
    course_taught << other_course unless self == other_course
  end

  # Unfollows a course.
  def remove_teacher_from_course(other_course)
    course_taught.delete(other_course)
  end

  # Returns true if the teacher is teaching other course.
  def course_taught?(other_course)
    course_taught.include?(other_course)
  end

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  def should_generate_new_friendly_id?
    name_changed?
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.find_for_database_authentication warden_condition
    conditions = warden_condition.dup
    login = conditions.delete(:login)
    where(conditions).where(
      ["lower(username) = :value OR lower(email) = :value",
      { value: login.strip.downcase}]).first
  end
end

app/controllers/teachers/confirmations_controller.rb
# frozen_string_literal: true

class Teachers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/teachers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Teachers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/teachers/passwords_controller.rb
# frozen_string_literal: true

class Teachers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/teachers/registrations_controller.rb
# frozen_string_literal: true

class Teachers::RegistrationsController < Devise::RegistrationsController
  before_action :teacher_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
    current_admin
  end

  # POST /resource
  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to admin_createteacher_path(current_admin), notice: "Teacher created successfully."
    else
      render :new
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the teacher wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  #If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:school_id])
  # end

  def teacher_params
    params.require(:teacher).permit(:username, :name, :email, :password, :password_confirmation, :school_id)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/teachers/sessions_controller.rb
# frozen_string_literal: true

class Teachers::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  def after_sign_in_path_for(resource)
    school_teacher_path(current_teacher.school, current_teacher)
  end

  def after_sign_out_path_for(resource)
    request.referrer || @teacher
  end
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :password_confirmation])
  end
end

app/controllers/teachers/unlocks_controller.rb
# frozen_string_literal: true

class Teachers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :current_teacher

  def show
    @teacher = Teacher.find(params[:id])
    current_admin
    @school = School.where(id: @teacher.school_id).first
    @schoolcourses = Course.where(:grade_id => @school.grades.ids)
    @schoolgrades = Grade.where(:school_id => @teacher.school_id)
    @gradecourses = Course.where(:grade_id => @teacher.grade_taught)

    if !(admin_signed_in? && current_admin.id == @school.admin_id || current_teacher == @teacher)
      if current_admin
        redirect_to school_path(current_admin.school.id)
      elsif current_student
        redirect_to school_path(current_student.school_id)
      elsif current_teacher
        redirect_to school_path(current_teacher.school_id)
      else
        redirect_to root_path
      end
      flash[:alert] = "You are not authorized!"
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/show.html.erb
<%= render 'schools/header' %>
<!-- Page Wrapper -->
<div id="wrapper">
  <!-- Sidebar -->
  <ul class="navbar-nav bg-gradient-success sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <% if current_admin %>
      <%= link_to current_admin, class: "sidebar-brand d-flex align-items-center justify-content-center" do %>
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="far fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Admin</div>
      <% end %>
    <% end %>
    <% if current_teacher %>
      <%= link_to [current_teacher.school, current_teacher], class: "sidebar-brand d-flex align-items-center justify-content-center" do %>
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="far fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Teacher</div>
      <% end %>
    <% end %>
    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
        <i class="fa fa-fw fa-folder"></i>
        <span>Courses</span>
      </a>
      <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <% @schoolcourses.each do |course| %>
            <% if @teacher.course_taught?(course) %>
              <%= link_to course.name.capitalize, school_grade_course_path(@school, course.grade, course), class: "collapse-item" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </li>
    <% if admin_signed_in? && current_admin.id == @school.admin_id %>
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePage" aria-expanded="true" aria-controls="collapsePages">
          <i class="fa fa-fw fa-folder"></i>
          <span>Manage Courses</span>
        </a>
        <div id="collapsePage" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <% @schoolcourses.each do |course| %>
              <%= link_to course.name.capitalize, school_grade_course_path(@school.id, course.grade, course), class: "collapse-item" %>
              <% if @teacher.course_taught?(course) %>
                <%= form_with(model: @teacher.active_teacher_courses.find_by(followed_id: course.id), html: { method: :delete }, local: true) do |f| %>
                  <%= hidden_field_tag :follower_id, @teacher.id %>
                  <%= f.submit "Unfollow" %>
                <% end %>
              <% else %>
                <%= form_with(model: @teacher.active_teacher_courses.build, local: true) do |f| %>
                  <div><%= hidden_field_tag :followed_id, course.id %><%= hidden_field_tag :follower_id, @teacher.id %></div>
                  <%= f.submit "Add Course" %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePag" aria-expanded="true" aria-controls="collapsePages">
          <i class="fa fa-fw fa-folder"></i>
          <span>Manage Grades</span>
        </a>
        <div id="collapsePag" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <% @schoolgrades.each do |grade| %>
              <% if grade.courses.any? %>
                <a class="collapse-item"><%= grade.name.capitalize %></a>
                <% if @teacher.grade_taught?(grade) %>
                  <%= form_with(model: @teacher.active_teacher_grades.find_by(followed_id: grade.id), html: { method: :delete }, local: true) do |f| %>
                    <%= hidden_field_tag :follower_id, @teacher.id %>
                    <%= f.submit "Unfollow" %>
                  <% end %>
                <% else %>
                  <%= form_with(model: @teacher.active_teacher_grades.build, local: true) do |f| %>
                    <div><%= hidden_field_tag :followed_id, grade.id %><%= hidden_field_tag :follower_id, @teacher.id %></div>
                    <%= f.submit "Add Grade" %>
                  <% end %>
                <% end %>
              <% else %>
                <%= link_to "Add at least 1 course", school_grade_path(grade.school, grade), class: "collapse-item" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
  </ul>
  <!-- End of Sidebar -->
  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content">
      <!-- Begin Page Content -->
      <div class="container-fluid mt-2">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
          <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
        </div>
        <!-- Content Row -->
        <div class="row">
          <!-- Area Chart -->
          <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
              <!-- Card Header - Dropdown -->
              <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-success"><%= @teacher.name.capitalize %>'s Performance</h6>
              </div>
              <!-- Card Body -->
              <div class="card-body">
                <div class="chart-area">
                  <canvas id="myAreaChart"></canvas>
                </div>
              </div>
            </div>
          </div>
          <!-- Pie Chart -->
          <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
              <!-- Card Header - Dropdown -->
              <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-success">Profile details</h6>
              </div>
              <!-- Card Body -->
              <div class="card-body">
                <div class="chart-pie pt-4 pb-2">
                  <div class="card" style="width: 100%;">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="180" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"></rect><text x="35%" y="50%" fill="#dee2e6" dy=".1em">Profile Picture</text></svg>
                    <div class="card-body">
                      <h5 class="card-title"><%= @teacher.name %></h5>
                    </div>
                  </div>
                </div>
                <div class="mt-4 text-center small">
                  <span class="mr-2">
                    <i class="fas fa-circle text-success"></i> Direct
                  </span>
                  <span class="mr-2">
                    <i class="fas fa-circle text-success"></i> Social
                  </span>
                  <span class="mr-2">
                    <i class="fas fa-circle text-info"></i> Referral
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Content Row -->
        <div class="row">
          <!-- Content Column -->
          <div class="col-lg-6 mb-4">
            <!-- Project Card Example -->
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-success">Courses: <%= @teacher.course_taught.count + @gradecourses.count %></h6>
              </div>
              <div class="card-body">
                <% @schoolcourses.each do |course| %>
                  <% if @teacher.course_taught?(course) %>
                    <h4 class="small font-weight-bold"><%= link_to course.name.capitalize, school_grade_course_path(@school, course.grade, course) %><span class="float-right">20%</span></h4>
                    <div class="progress mb-4">
                      <div class="progress-bar bg-danger" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-lg-6 mb-4">
            <!-- Illustrations -->
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-success">Forum</h6>
              </div>
              <div class="card-body">
                <div class="text-center">
                  <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="img/undraw_posting_photo.svg" alt="">
                </div>
                <p>Add some quality, svg illustrations to your project courtesy of <a target="_blank" rel="nofollow" href="https://undraw.co/">unDraw</a>, a constantly updated collection of beautiful svg images that you can use completely free and without attribution!</p>
                <a target="_blank" rel="nofollow" href="https://undraw.co/">Browse Illustrations on unDraw &rarr;</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- End of Main Content -->
    <!-- Footer -->
    <footer class="sticky-footer bg-white">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright &copy; Your Website 2020</span>
        </div>
      </div>
    </footer>
    <!-- End of Footer -->
  </div>
  <!-- End of Content Wrapper -->
</div>
<!-- End of Page Wrapper -->