config/routes.rb
require "custom_domain"

Rails.application.routes.draw do
  constraints CustomDomain do
    root to: "schools#show" do
      get "admin", to: "admins#show"
      devise_scope :student do
        get "students/sign_in", to: "students/sessions#new"
        get "students/sign_out", to: "students/sessions#destroy"
      end
      devise_scope :teacher do
        get "teachers/sign_in", to: "teachers/sessions#new"
        get "teachers/sign_out", to: "teachers/sessions#destroy"
      end
      resources :blogs
      resources :grades, only: [:edit, :create, :destroy, :update, :show] do
        resources :courses, only: [:show] do
          member do
            get :followers, :course_teachers
          end
        end
        member do
          get :grade_teachers
        end
      end
      resources :students, only: [:show] do
        member do
          get :following
        end
      end
      resources :teachers, only: [:show] do
        member do
          get :grade_taught, :course_taught
        end
      end
    end
  end

  devise_for :admins, controllers: {
                        registrations: "admins/registrations",
                        sessions: "admins/sessions",
                      }
  devise_for :students, controllers: {
                          registrations: "students/registrations",
                          sessions: "students/sessions",
                        }
  devise_for :teachers, controllers: {
                          registrations: "teachers/registrations",
                          sessions: "teachers/sessions",
                        }
  resources :notes
  resources :tests
  resources :assignments
  resources :test_scores
  resources :assignment_scores
  resources :blogs
  resources :courses, only: [:edit, :create, :destroy, :update]
  resources :schools, except: [:destroy] do
    devise_scope :student do
      get "students/sign_in", to: "students/sessions#new"
      get "students/sign_out", to: "students/sessions#destroy"
    end
    devise_scope :teacher do
      get "teachers/sign_in", to: "teachers/sessions#new"
      get "teachers/sign_out", to: "teachers/sessions#destroy"
    end
    resources :blogs
    resources :grades, only: [:edit, :create, :destroy, :update, :show] do
      resources :courses, only: [:show] do
        member do
          get :followers, :course_teachers
        end
      end
      member do
        get :grade_teachers
      end
    end
    resources :students, only: [:show] do
      member do
        get :following
      end
    end
    resources :teachers, only: [:show] do
      member do
        get :grade_taught, :course_taught
      end
    end
  end

  get "/", to: "home#index"

  resources :admins, :only => [:show] do
    get "/createstudent", to: "admins#create_students"
    get "/createteacher", to: "admins#create_teachers"
    get "/classes", to: "admins#classes"
    get "/posts", to: "admins#posts"
    get "/domain", to: "admins#domain"
  end
  resources :student_courses, only: [:create, :destroy]
  resources :teacher_courses, only: [:create, :destroy]
  resources :teacher_grades, only: [:create, :destroy]
  get "schools/:id/admin", to: "admins#show"
end

app/models/school.rb
class School < ApplicationRecord
  after_save :update_heroku_domains if :domain.present?

  mount_uploader :logo, FileUploader
  serialize :logo, JSON

  has_many :students
  has_many :grades
  has_many :blogs
  belongs_to :admin, class_name: "Admin", foreign_key: "admin_id"
  extend FriendlyId
  friendly_id :uuid, use: [:slugged, :finders]

  private

  def update_heroku_domains
    if self.domain_changed? && self.domain_was.present?
      HerokuDomainJob.perform_later(self.domain_was, "remove")
    end
    HerokuDomainJob.perform_later(self.domain, "add")
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :find_school, only: :show
  before_action :set_school, only: [:edit, :update, :destroy]

  def index
    @schools = School.all
  end

  def show
    check_signed_user
    @blogs = Blog.where(school_id: @school.id)
  end

  def new
    @school = School.new
  end

  def edit
  end

  def create
    @school = current_admin.create_school(school_params)
    respond_to do |format|
      if @school.save
        format.html { redirect_to current_admin, notice: "School was successfully created." }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: "School was successfully updated." }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def find_school
    @school = School.find_by(domain: request.host) || School.find(params[:id])
  end

  def set_school
    @school = School.find(params[:id])
  end

  def school_params
    params.require(:school).permit(:name, :description, :logo, :banking, :address, :contact, :domain)
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
  def replace_url(school)
    if school.domain.present?
      school = SecureRandom.hex(3)
    else
      school = school
    end
    return school
  end
end

app/views/schools/_footer.html.erb
<!-- Footer -->
 <div class="container-fluid pb-0 mb-0 bg-dark justify-content-center text-light ">
     <footer class="bg-dark my-0">
         <div class="row justify-content-center py-5">
             <div class="col-11">
                 <div class="row ">
                     <div class="col-xl-8 col-md-4 col-sm-4 col-12 my-auto mx-auto a">
                         <% if @school.logo_url %>
                           <img src="<%= @school.logo_url %>" width="150" height="150" class="img-fluid" />
                           <h3 class="text-muted mb-md-0 mb-5 bold-text"><%= @school.name %></h3>
                         <% else %>
                           <h3 class="text-muted mb-md-0 mb-5 bold-text"><%= @school.name %></h3>
                         <% end %>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-12">
                         <h6 class="mb-3 mb-lg-4 bold-text "><b>MENU</b></h6>
                         <ul class="list-unstyled">
                             <li>Home</li>
                             <li>About</li>
                             <li>Blog</li>
                             <li>Portfolio</li>
                         </ul>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-12">
                         <h6 class="mb-3 mb-lg-4 text-muted bold-text mt-sm-0 mt-5"><b>ADDRESS</b></h6>
                         <% if @school.address %>
                           <p class="mb-1"><%= @school.address %></p>
                         <% else %>
                           <p class="mb-1">This school does <br>not have an address</p>
                         <% end %>
                     </div>
                 </div>
                 <div class="row ">
                     <div class="col-xl-8 col-md-4 col-sm-4 col-auto my-md-0 mt-5 order-sm-1 order-3 align-self-end">
                         <p class="social text-muted mb-0 pb-0 bold-text"> 
                         <span class="mx-2"><i class="fa fa-facebook" aria-hidden="true"></i></span> 
                         <span class="mx-2"><i class="fa fa-linkedin-square" aria-hidden="true"></i></span> 
                         <span class="mx-2"><i class="fa fa-twitter" aria-hidden="true"></i></span> 
                         <span class="mx-2"><i class="fa fa-instagram" aria-hidden="true"></i></span> 
                         </p>
                         <small class="rights">
                         <span>&copy;</span> <%= @school.name %> <%= Time.current.year %>
                         </small>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-1 align-self-end ">
                         <h6 class="mt-55 mt-2 text-muted bold-text"><b>Contact</b></h6>
                         <small> 
                         <span><i class="fa fa-envelope" aria-hidden="true"></i></span>
                         <% if @school.contact %>
                           <p class="mb-1"><%= @school.contact %></p>
                         <% else %>
                           <p class="mb-1">This school does <br>not have contact details</p>
                         <% end %>
                         </small>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-2 align-self-end mt-3 ">
                         <h6 class="text-muted bold-text"><b>Banking details</b></h6>
                         <small>
                         <span><i class="fa fa-envelope" aria-hidden="true"></i></span> 
                         <% if @school.banking %>
                           <p class="mb-1"><%= @school.banking %></p>
                         <% else %>
                           <p class="mb-1">This school does <br>not have any banking details</p>
                         <% end %>
                         </small>
                     </div>
                 </div>
             </div>
         </div>
     </footer>
 </div>

app/views/schools/_form.html.erb
<div class="container-fluid">
  <div class="row no-gutter">
    <div class="d-md-flex col-md-4 col-lg-6 bg-image align-items-center px-5 py-5" style='background-image: url(<%= image_url("bg.jpg") %>)'>
      <p><b>Now fill all the required details, the name of the school which will be used on the school page. If you do not have a logo you can leave it blank.</b></p>
    </div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
               <%= form_with(model: school, local: true) do |form| %>
            <% if school.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>
                <ul>
                  <% school.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="field">
              <div class="control">
              <%= form.label :name %>
              <%= form.text_field :name, required: true, class:"form-control", placeholder: "Schoolname high" %>
            </div>
            </div>
            <div class="field">
            <div class="control">
              <%= form.label :description %>
              <%= form.text_area :description, required: true, class:"form-control" %>
            </div>
            </div>
             <div class="field">
              <div class="control">
              <%= form.label :address %>
              <%= form.text_field :address, required: true, class:"form-control" %>
            </div>
            </div>
             <div class="field">
              <div class="control">
              <%= form.label :domain %>
              <%= form.text_field :domain, class:"form-control" %>
            </div>
            </div>
            <div class="field">
            <div class="control">
              <%= form.label :contact %>
              <%= form.text_area :contact, required: true, class:"form-control" %>
            </div>
            </div>
             <div class="field">
              <div class="control">
              <%= form.label :logo %>
              <%= form.file_field :logo, class:"form-control" %>
            </div>
            </div>
            <div class="field">
            <div class="control">
              <%= form.label :banking %>
              <%= form.text_area :banking, class:"form-control" %>
              <small class="form-text text-muted">Enter school banking details which will show at the bottom of page</small>
            </div>
            </div>
            <div class="field">
            <div class="control">
              <%= form.button :submit, class: "btn btn-success is-medium" %>
            </div>
            </div>
          <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/schools/_header.html.erb
 <!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <% if teacher_signed_in? %>
      <%= link_to current_teacher.school.name.capitalize, current_teacher.school, class: "navbar-brand" %>
    <% elsif admin_signed_in? %>
      <% if current_admin.school != nil %>
        <%= link_to current_admin.school.name.capitalize, current_admin.school, class: "navbar-brand" %>
      <% else %>
        <%= link_to "create school",  new_school_path, class: "navbar-brand" %>
      <% end %>
    <% elsif student_signed_in? %>
      <% if current_student.school.domain.present? %>
        <%= link_to current_student.school.name.capitalize, current_student.school,  class: "navbar-brand" %>
      <% else %>
        <%= link_to current_student.school.name.capitalize, current_student.school,  class: "navbar-brand" %>
      <% end %>
    <% elsif %>
      <%= link_to @school.name.capitalize, @school, class: "navbar-brand" %>
    <% end %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if !admin_signed_in? %>
          <% if !student_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Stuff
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <% if teacher_signed_in? %>
                  <%= link_to current_teacher.name, [current_teacher.school, current_teacher], class: "dropdown-item" %>
                  <%= link_to "Go home to Log Out", current_teacher.school, class: "dropdown-item" %>
                <% else %>
                  <%= link_to "Sign In", school_teachers_sign_in_path, class: "dropdown-item" %>
                <% end %>
              </div>
            </li>
          <% end %>
          <% if !teacher_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Student
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <% if student_signed_in? %>
                  <%= link_to current_student.name, [current_student.school, current_student], class: "dropdown-item" %>
                  <%= link_to "Go home to Log Out", current_student.school, class: "dropdown-item" %>
                <% else %>
                  <%= link_to "Sign In", school_students_sign_in_path, class: "dropdown-item" %>
                <% end %>
              </div>
            </li>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Dashboard", current_admin, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/schools/_logo_checker.html.erb
<% if teacher_signed_in? %>
  <% if @school.logo_url.present? %>
    <%= link_to current_teacher.school, class: "navbar-brand" do %>
      <img src="<%= @school.logo_url %>" width="50" height="50" class="img-fluid" />
      <small><%= current_teacher.school.name.capitalize %></small>
    <% end %>
  <% else %>
    <%= link_to current_teacher.school.name.capitalize, current_teacher.school, class: "navbar-brand" %>
  <% end %>
<% elsif admin_signed_in? %>
  <% if current_admin.school != nil %>
    <% if @school.logo_url.present? %>
      <%= link_to current_admin.school, class: "navbar-brand" do %>
        <img src="<%= @school.logo_url %>" width="50" height="50" class="img-fluid" />
        <small><%= current_admin.school.name.capitalize %></small>
      <% end %>
    <% else %>
      <%= link_to current_admin.school.name.capitalize, current_admin.school, class: "navbar-brand" %>
    <% end %>
  <% else %>
    <%= link_to "create school",  new_school_path, class: "navbar-brand" %>
  <% end %>
<% elsif student_signed_in? %>
  <% if @school.logo_url.present? %>
    <%= link_to current_student.school, class: "navbar-brand" do %>
      <img src="<%= @school.logo_url %>" width="50" height="50" class="img-fluid" />
      <small><%= current_student.school.name.capitalize %></small>
    <% end %>
  <% else %>
    <%= link_to current_student.school.name.capitalize, current_student.school, class: "navbar-brand" %>
  <% end %>
<% elsif %>
  <% if @school.logo_url.present? %>
    <%= link_to @school, class: "navbar-brand" do %>
      <img src="<%= @school.logo_url %>" width="50" height="50" class="img-fluid" />
      <small><%= @school.name.capitalize %></small>
    <% end %>
  <% else %>
    <%= link_to @school.name.capitalize, @school, class: "navbar-brand" %>
  <% end %>
<% end %>

app/views/schools/_main_header.html.erb
  <!-- Navigation -->
<nav class="navbar navbar-expand-lg fixed-top navbar-light inde" id="mainNav">
  <div class="container">
    <%= render '/schools/logo_checker' %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if !admin_signed_in? %>
          <% if !student_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Stuff
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <% if teacher_signed_in? %>
                  <%= link_to current_teacher.name, [current_teacher.school, current_teacher], class: "dropdown-item" %>
                  <%= link_to "Log Out", destroy_teacher_session_path, method: :delete, class: "dropdown-item" %>
                <% else %>
                  <%= link_to "Sign In", school_teachers_sign_in_path(@school.id), class: "dropdown-item" %>
                <% end %>
              </div>
            </li>
          <% end %>
          <% if !teacher_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Student
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <% if student_signed_in? %>
                  <%= link_to current_student.name, [current_student.school, current_student], class: "dropdown-item" %>
                  <%= link_to "Log Out", destroy_student_session_path, method: :delete, class: "dropdown-item" %>
                <% else %>
                  <%= link_to "Sign In", school_students_sign_in_path(@school.id), class: "dropdown-item" %>
                <% end %>
              </div>
            </li>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Dashboard", current_admin, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/schools/_schoolform.html.erb
<%= form_with(model: School.new, remote: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, required: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, required: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :contact %>
    <%= form.text_field :contact, required: true, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= form.label :banking %>
    <%= form.text_field :banking, class: "form-control" %>
    <small class="lead">Enter school banking details</small>
  </div>
  <div class="form-group">
    <%= form.label :logo %>
    <%= form.file_field :logo, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<%= render 'layouts/header' %>
<h1>Schools</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.description %></td>
        <td><%= link_to 'Show', school %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/schools/new.html.erb
<% if admin_signed_in? && !current_admin.school %>
<%= render 'form', school: @school %>
<% else %>
    <h1 class="text-center pt-3">You are not authorized!</h1>
<% end %>

app/views/schools/show.html.erb
<%= render 'main_header' %>
<!-- Page Content -->
<!-- Page Header -->
<header class="masthead" style='background-image: url(<%= image_url("home-bg.jpg") %>)'>
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Welcome to</h1>
          <span class="subheading"><%=  @school.name %></span>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <h1 class="my-4">Latest news</h1>
  <!-- Marketing Icons Section -->
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <% if @blogs.any? %>
        <% @blogs.each do |blog| %>
          <div class="post-preview row">
            <div class="col-lg-4 col-md-10 mx-auto blog-image">
              <%= link_to school_blog_path(blog.school, blog) do %>
                <%= image_tag blog.image_url class: "card-img-top" %>
              <% end %>
            </div>
            <div class="col-lg-8 col-md-10 mx-auto">
              <%= link_to school_blog_path(blog.school, blog) do %>
                <h2 class="post-title">
                  <%= blog.title %>
                </h2>
                <h3 class="post-subtitle">
                  <%= blog.description %>
                </h3>
              <% end %>
              <p class="post-meta">Posted on <%= blog.created_at %>
              </p>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="post-preview row">
          <div class="col-lg-4 col-md-10 mx-auto blog-image">
            <a href="#">
              <img class="card-img-top" src="http://placehold.it/700x400" alt="">
            </a>
          </div>
          <div class="col-lg-8 col-md-10 mx-auto">
            <a href="#">
              <h2 class="post-title">
                This is a post generated by the system
              </h2>
            </a>
            <p class="post-meta">Posted on 18 April, 2021
            </p>
          </div>
        </div>
      <% end %>
      <hr>
      <!-- Pager -->
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
  <!-- /.row -->
  <!-- Portfolio Section -->
  <!-- <h2>School gallery</h2>
  <div class="row">
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="#">Project One</a>
          </h4>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="#">Project Two</a>
          </h4>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="#">Project Three</a>
          </h4>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="#">Project Four</a>
          </h4>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="#">Project Five</a>
          </h4>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="#">Project Six</a>
          </h4>
        </div>
      </div>
    </div>
  </div> -->
  <!-- /.row -->
</div>
<div class="container-fluid cale mt-5 py-5">
  <div class="row py-5">
    <div class="col-lg-8 mx-auto">

      <div class="card mb-4">
        <div class="card-body p-5">
          <h4 class="mb-4">About <%= @school.name %></h4>
          <div class="custom-scrollbar-css p-2">
            <p class="font-italic"><%= @school.description %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- For Demo Purpose -->
  <header class="text-center text-white mb-5">
    <h1 class="display-4">School Calendar</h1>
    <p class="font-italic mb-0">Get the upcoming events</p>
  </header>

  <!-- Calendar -->
  <div class="calendar shadow bg-white p-5">
    <div class="d-flex align-items-center"><i class="fa fa-calendar fa-3x mr-3"></i>
      <h2 class="month font-weight-bold mb-0 text-uppercase">December 2019</h2>
    </div>
    <p class="font-italic text-muted mb-5">No events for this day.</p>
    <ol class="day-names list-unstyled">
      <li class="font-weight-bold text-uppercase">Sun</li>
      <li class="font-weight-bold text-uppercase">Mon</li>
      <li class="font-weight-bold text-uppercase">Tue</li>
      <li class="font-weight-bold text-uppercase">Wed</li>
      <li class="font-weight-bold text-uppercase">Thu</li>
      <li class="font-weight-bold text-uppercase">Fri</li>
      <li class="font-weight-bold text-uppercase">Sat</li>
    </ol>

    <ol class="days list-unstyled">
      <li>
        <div class="date">1</div>
        <div class="event bg-success">Event with Long Name</div>
      </li>
      <li>
        <div class="date">2</div>
      </li>
      <li>
        <div class="date">3</div>
      </li>
      <li>
        <div class="date">4</div>
      </li>
      <li>
        <div class="date">5</div>
      </li>
      <li>
        <div class="date">6</div>
      </li>
      <li>
        <div class="date">7</div>
      </li>
      <li>
        <div class="date">8</div>
      </li>
      <li>
        <div class="date">9</div>
      </li>
      <li>
        <div class="date">10</div>
      </li>
      <li>
        <div class="date">11</div>
      </li>
      <li>
        <div class="date">12</div>
      </li>
      <li>
        <div class="date">13</div>
        <div class="event all-day begin span-2 bg-warning">Event Name</div>
      </li>
      <li>
        <div class="date">14</div>
      </li>
      <li>
        <div class="date">15</div>
        <div class="event all-day end bg-success">Event Name</div>
      </li>
      <li>
        <div class="date">16</div>
      </li>
      <li>
        <div class="date">17</div>
      </li>
      <li>
        <div class="date">18</div>
      </li>
      <li>
        <div class="date">19</div>
      </li>
      <li>
        <div class="date">20</div>
      </li>
      <li>
        <div class="date">21</div>
        <div class="event bg-primary">Event Name</div>
        <div class="event bg-success">Event Name</div>
      </li>
      <li>
        <div class="date">22</div>
        <div class="event bg-info">Event with Longer Name</div>
      </li>
      <li>
        <div class="date">23</div>
      </li>
      <li>
        <div class="date">24</div>
      </li>
      <li>
        <div class="date">25</div>
      </li>
      <li>
        <div class="date">26</div>
      </li>
      <li>
        <div class="date">27</div>
      </li>
      <li>
        <div class="date">28</div>
      </li>
      <li>
        <div class="date">29</div>
      </li>
      <li>
        <div class="date">30</div>
      </li>
      <li>
        <div class="date">31</div>
      </li>
      <li class="outside">
        <div class="date">1</div>
      </li>
      <li class="outside">
        <div class="date">2</div>
      </li>
      <li class="outside">
        <div class="date">3</div>
      </li>
      <li class="outside">
        <div class="date">4</div>
      </li>
    </ol>
  </div>
</div>
<!-- /.container -->
<%= render 'schools/footer' %>